apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xy6roqa1c-dotnet-basic-gitops
  description: This is GitOps manifest for xy6roqa1c-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: xy6roqa1c-dotnet-basic
    backstage.io/kubernetes-id: xy6roqa1c-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xy6roqa1c-dotnet-basic
