apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xy6roqa1c-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xy6roqa1c-dotnet-basic-gitops