apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xy6roqa1c-dotnet-basic
  janus-idp.io/tekton: xy6roqa1c-dotnet-basic
  backstage.io/kubernetes-id: xy6roqa1c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy6roqa1c-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
